name: Integração continua

on:
  push:
    branches:
      - main
      - master

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Realiza o checkout
      - uses: actions/checkout@v2

      - name: Run a script
      - run: echo Hello, world!